

const start = async () => {
	try {
		
	} catch (e) {
		console.log(e)
	}
	
}